BASE_TASK_CONFIG_PATH: "configs/challenge_objectnav2020.local.rgbd.yaml"
TRAINER_NAME: "ddppo"
ENV_NAME: "NavRLEnv"
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
VIDEO_OPTION: []
TENSORBOARD_DIR: "tb"
VIDEO_DIR: "video_dir"
TEST_EPISODE_COUNT: 994
EVAL_CKPT_PATH_DIR: "data/new_checkpoints"
NUM_PROCESSES: 4
SENSORS: ["RGB_SENSOR" , "DEPTH_SENSOR"]
CHECKPOINT_FOLDER: "data/new_checkpoints"
NUM_UPDATES: 10000
LOG_INTERVAL: 10
CHECKPOINT_INTERVAL: 50

RL:
  SUCCESS_REWARD: 2.5
  SLACK_REWARD: -0.001
  COVERAGE_REWARD: 0.1
  PPO:
    clip_param: 0.1
    ppo_epoch: 4
    num_mini_batch: 2
    value_loss_coef: 0.5
    entropy_coef: 0.01
    lr: 2.5e-4
    eps: 1e-5
    max_grad_norm: 0.5
    num_steps: 128
    hidden_size: 228
    use_gae: True
    gamma: 0.99
    tau: 0.95
    use_linear_clip_decay: False
    use_linear_lr_decay: False
    use_normalized_advantage: False
    reward_window_size: 50
    policy: "TRANSFORMER_IM_BELIEF"
    POLICY:
      use_mean_and_var: True
  AUX_TASKS:
    tasks: ["CPCA", "CPCA_A", "CPCA_B", "GID", "ActionDist", "ActionDist_A"]
    entropy_coef: 0.1
    CPCA:
      num_steps: 4
    CPCA_A:
      num_steps: 8
    CPCA_B:
      num_steps: 16
    GID:
      loss_factor: 0.1
      num_steps: 4
    ActionDist:
      loss_factor: 0.25
      num_steps: -4
    ActionDist_A:
      loss_factor: 0.25
      num_steps: 6